[project]
name = "primal-vrp"
version = "0.1.0"
description = "A minimalist, high-performance engine for CPDPTW optimization."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.1.0",
    "networkx>=3.3",
    "requests>=2.32.3",
    "fastapi>=0.115.0",
    "uvicorn>=0.30.6",
    "pydantic>=2.9.2",
    "numba>=0.60.0",
]

[project.optional-dependencies]
test = [
    "pytest>=8.3.3",
    "httpx>=0.27.2",
    "ruff>=0.6.9",
]
benchmark = [
    "ortools>=9.11.4210",
]

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:builtin type SwigPyPacked has no __module__ attribute",
    "ignore:builtin type SwigPyObject has no __module__ attribute",
    "ignore:builtin type swigvarlink has no __module__ attribute",
]
